name: agromant
services:
  mongodb:
    image: mongo:6.0
    profiles:
      - environment
      - development
    container_name: agromant_mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - agromant-mongo-data:/data/db

  mongo-express:
    image: mongo-express:1.0.0
    profiles:
      - environment
      - development
    container_name: agromant_mongo_express
    restart: always
    env_file:
      - .env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER}
      - ME_CONFIG_MONGODB_PORT=${ME_CONFIG_MONGODB_PORT}
      - ME_CONFIG_OPTIONS_AUTH_SOURCE=${ME_CONFIG_OPTIONS_AUTH_SOURCE}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
  app:
    build:
      context: ./bot
      dockerfile: Dockerfile
    profiles:
      - development
    container_name: agromant_app
    restart: always
    env_file:
      - .env
    ports:
      - "8443:8443"
    depends_on:
      - mongodb

volumes:
  agromant-mongo-data:
    driver: local